name: devforge-suite # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title:  DevForge Tools
summary: Supercharge your development workflow.
description:  A powerful suite for software development with project scaffolding, code templates, and integrated terminal support across multiple languages.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  devforge-suite:
    command: bin/devforge-suite-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  devforge-suite:
    plugin: dump
    source: .
    organize:
      devforge-suite-bin: bin/
